# Website Information
site_name: "My IT Journal"
site_author: "Davide Verardo"
edit_uri: "edit/main/docs"

# Repository
repo_name: dv23m236/myitjournal
repo_url: https://github.com/dv23m236/myitjournal

# Configuration
theme:
  features: 
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    # - navigation.sections
    # - navigation.expand
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil
  palette: 
  - scheme: default
    primary: black
    accent: black
    toggle:
      icon: material/weather-night      
      name: Switch to dark mode
  - scheme: slate
    primary: white
    accent: white
    toggle:
      icon: material/weather-sunny      
      name: Switch to light mode
