[project]
site_name = "My IT Journal"
site_url = "https://dv23m236.github.io/myitjournal/"
site_author = "Your Name"
copyright = 'Copyright &copy; 2026 Your Name<br />Licensed under CC BY-SA 4.0'

# Repository Shortcut
repo_name = "dv23m236/myitjournal"
repo_url = "https://github.com/dv23m236/myitjournal"

# The Navigation (Must match your actual folder/file names!)
nav = [
    { "Home" = "index.md" },
    { "Guides" = [
        { "Zensical" = "guides/zensical.md" },
        { "Git & GitHub" = "guides/git.md" },
    ] },
    { "About Me" = "about.md" },
]

[project.theme]
name = "material"
variant = "classic"
features = [
    "navigation.tabs",
    "navigation.top",
    "search.highlight",
]

# Color Toggles (Light/Dark mode)
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
toggle.icon = "material/weather-night"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to light mode"