[project]
site_name = "My IT Journal"
site_url = "https://dv23m236.github.io/myitjournal/"
site_author = "Davide"
copyright = 'Copyright &copy; 2026 Davide<br />Licensed under CC BY-SA 4.0'

# Repository Shortcut
repo_name = "dv23m236/myitjournal"
repo_url = "https://github.com/dv23m236/myitjournal"

extra_css = ["stylesheets/extra.css"]

# The Navigation (Must match your actual folder/file names!)
nav = [
    { "Home" = "index.md" },
    { "Guides" = [
        { "Conda Grundlagen" = "guides/conda_basics.md" },
        { "Zensical Environment" = "guides/zensical_env.md" },
        { "Git & Erstes Projekt" = "guides/git_project.md" },
        { "GitHub Pages" = "guides/github_pages.md" }
        
    ] },
    { "Reference" = "reference.md" },

    { "Weekly Journal" = [
        { "Week 21" = "weeklys/week-21.md" },
        { "Week 20" = "weeklys/week-20.md" },
        { "Week 19" = "weeklys/week-19.md" },
        { "Week 18" = "weeklys/week-18.md" },
        { "Week 17" = "weeklys/week-17.md" }
    ]},
    { "About Me" = "about.md" }
]


[project.markdown_extensions]
admonition = {}
attr_list = {}
md_in_html = {}
footnotes = {}
sane_lists = {}

[project.markdown_extensions.pymdownx.details] # Enables the ??? info "Title" dropdowns
[project.markdown_extensions.pymdownx.highlight] # Better code blocks and text highlights
[project.markdown_extensions.pymdownx.inlinehilite] # Inline code highlight support
[project.markdown_extensions.pymdownx.keys]      # Enables keyboard key styling e.g., ++ctrl+alt+del++
[project.markdown_extensions.pymdownx.snippets]  # Allows pulling code snippets from other files
[project.markdown_extensions.pymdownx.magiclink] # Auto-links bare URLs or emails

[project.markdown_extensions.pymdownx.mark]          # Fixes: ==marked text==
[project.markdown_extensions.pymdownx.tilde]         # Fixes: ~~strikethrough~~ and H~2~O subscripts
[project.markdown_extensions.pymdownx.caret]         # Fixes: ^^underline^^ and A^T^A superscripts

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.tasklist]      # Fixes: Turns [x] into real checkboxes
custom_checkbox = true                               # Makes them look native and clean

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.theme]
variant = "modern"
name = "material"
features = [
    "navigation.tabs",         # Top level menu as tabs
    "navigation.sections",     # Groups navigation into sections
    "navigation.expand",       # Left sidebar starts expanded
    "navigation.top",          # The "Back to Top" button
    "navigation.tabs.sticky",  # Keeps that menu fixed while you scroll
    "toc.follow",              # Right sidebar highlights as you scroll
    "navigation.tracking",     # Highlights where you are as you scroll
    "navigation.indexes",      # Allows clicking a folder name to open a page
    "search.suggest",          # Better search bar
    "search.highlight",        # Highlights search results
    "content.tooltips"
]

[project.markdown_extensions.toc]
permalink = true
toc_depth = 3

[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"

[project.theme.icon]
logo = "material/home"


# Color Toggles (Light/Dark mode)
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "blue"
toggle.icon = "material/weather-night"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "Hotpink"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
